//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Alerts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you couldn&apos;t make operation month is Closed.
        /// </summary>
        internal static string checkmonthisclosed {
            get {
                return ResourceManager.GetString("checkmonthisclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        internal static string DataSavedSuccessfully {
            get {
                return ResourceManager.GetString("DataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to delete selected items.
        /// </summary>
        internal static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education type.
        /// </summary>
        internal static string Educationtype {
            get {
                return ResourceManager.GetString("Educationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Date.
        /// </summary>
        internal static string EffectDate {
            get {
                return ResourceManager.GetString("EffectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,Member In Service you should Insert Leave Frist.
        /// </summary>
        internal static string Empinleave {
            get {
                return ResourceManager.GetString("Empinleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Member out of service, you couldn&apos;t make any transaction.
        /// </summary>
        internal static string EmpoutofService {
            get {
                return ResourceManager.GetString("EmpoutofService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Visits Not Fully Conducted.
        /// </summary>
        internal static string EvalutionVisitsNotFullConducted {
            get {
                return ResourceManager.GetString("EvalutionVisitsNotFullConducted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Visits Not Fully Reviewed.
        /// </summary>
        internal static string EvalutionVisitsNotFullReviewed {
            get {
                return ResourceManager.GetString("EvalutionVisitsNotFullReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail To Save Data.
        /// </summary>
        internal static string FailToSaveData {
            get {
                return ResourceManager.GetString("FailToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, return date must not exceed end of the currnt month.
        /// </summary>
        internal static string leavemustnotexceedcurrnt {
            get {
                return ResourceManager.GetString("leavemustnotexceedcurrnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Will expire with in.
        /// </summary>
        internal static string LicenseWillexpirewithin {
            get {
                return ResourceManager.GetString("LicenseWillexpirewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load leave failed.
        /// </summary>
        internal static string loadleavefailed {
            get {
                return ResourceManager.GetString("loadleavefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan ref.
        /// </summary>
        internal static string Loanref {
            get {
                return ResourceManager.GetString("Loanref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Contract Will expire with in.
        /// </summary>
        internal static string MemberContractWillexpirewithin {
            get {
                return ResourceManager.GetString("MemberContractWillexpirewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member License Will expire with in.
        /// </summary>
        internal static string MemberLicenseWillexpirewithin {
            get {
                return ResourceManager.GetString("MemberLicenseWillexpirewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member passport Will expire with in.
        /// </summary>
        internal static string MemberpassportWillexpirewithin {
            get {
                return ResourceManager.GetString("MemberpassportWillexpirewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Recidancy Will expire with in.
        /// </summary>
        internal static string MemberRecidancyWillexpirewithin {
            get {
                return ResourceManager.GetString("MemberRecidancyWillexpirewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Will return from leave with in.
        /// </summary>
        internal static string MemberWillreturnfromleavewithin {
            get {
                return ResourceManager.GetString("MemberWillreturnfromleavewithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Close Last Month frist,to generate salary the current.
        /// </summary>
        internal static string monthclose {
            get {
                return ResourceManager.GetString("monthclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you couldn&apos;t delete, month is Closed.
        /// </summary>
        internal static string monthisclosed {
            get {
                return ResourceManager.GetString("monthisclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month locked Successfully.
        /// </summary>
        internal static string MonthlockedSuccessfully {
            get {
                return ResourceManager.GetString("MonthlockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,There is an opned Leave, you can not add multi leave.
        /// </summary>
        internal static string multileave {
            get {
                return ResourceManager.GetString("multileave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry No closed Month with selected month and year.
        /// </summary>
        internal static string noclosed {
            get {
                return ResourceManager.GetString("noclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opration Done successfully.
        /// </summary>
        internal static string oprationDonesuccessfully {
            get {
                return ResourceManager.GetString("oprationDonesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Enter.
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter arabic frist name.
        /// </summary>
        internal static string PleaseEnterarabicfristname {
            get {
                return ResourceManager.GetString("PleaseEnterarabicfristname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter arabic secand name.
        /// </summary>
        internal static string PleaseEnterarabicsecandname {
            get {
                return ResourceManager.GetString("PleaseEnterarabicsecandname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter arabic third name.
        /// </summary>
        internal static string PleaseEnterarabicthirdname {
            get {
                return ResourceManager.GetString("PleaseEnterarabicthirdname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter Basic Salary.
        /// </summary>
        internal static string PleaseEnterBasicSalary {
            get {
                return ResourceManager.GetString("PleaseEnterBasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter english frist name.
        /// </summary>
        internal static string PleaseEnterenglishfristname {
            get {
                return ResourceManager.GetString("PleaseEnterenglishfristname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter english secand name.
        /// </summary>
        internal static string PleaseEnterenglishsecandname {
            get {
                return ResourceManager.GetString("PleaseEnterenglishsecandname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,Enter Leave Balance.
        /// </summary>
        internal static string PleaseEnterLeaveBalance {
            get {
                return ResourceManager.GetString("PleaseEnterLeaveBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Year.
        /// </summary>
        internal static string PleaseEnterYear {
            get {
                return ResourceManager.GetString("PleaseEnterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseSelect.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseSelectbank.
        /// </summary>
        internal static string Pleaseselectbank {
            get {
                return ResourceManager.GetString("Pleaseselectbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseSelectMember.
        /// </summary>
        internal static string pleaseselectMember {
            get {
                return ResourceManager.GetString("pleaseselectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select month.
        /// </summary>
        internal static string PleaseSelectmonth {
            get {
                return ResourceManager.GetString("PleaseSelectmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select questions to evaluation append.
        /// </summary>
        internal static string PleaseselectQuestiontoTransfer {
            get {
                return ResourceManager.GetString("PleaseselectQuestiontoTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question transferred successfully.
        /// </summary>
        internal static string QuestionTransferedsuccessfully {
            get {
                return ResourceManager.GetString("QuestionTransferedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to  Generate  salary.
        /// </summary>
        internal static string salaryfaild {
            get {
                return ResourceManager.GetString("salaryfaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Generated Suceessfully.
        /// </summary>
        internal static string SalaryGeneratedSuceessfully {
            get {
                return ResourceManager.GetString("SalaryGeneratedSuceessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Delete Data Failed.
        /// </summary>
        internal static string SorryDeleteDataFailed {
            get {
                return ResourceManager.GetString("SorryDeleteDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete record, please delete related data first.
        /// </summary>
        internal static string SorryDeleteMaterDataFailed {
            get {
                return ResourceManager.GetString("SorryDeleteMaterDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Fail To retrive Data.
        /// </summary>
        internal static string SorryFailToretriveData {
            get {
                return ResourceManager.GetString("SorryFailToretriveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,Member In Leave.
        /// </summary>
        internal static string SorryMemberInLeave {
            get {
                return ResourceManager.GetString("SorryMemberInLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youhave.
        /// </summary>
        internal static string youhave {
            get {
                return ResourceManager.GetString("youhave", resourceCulture);
            }
        }
    }
}
