//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CTOS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CTOS() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CTOS", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agent Backload Container.
        /// </summary>
        internal static string AgentBackloadContainer {
            get {
                return ResourceManager.GetString("AgentBackloadContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agent Containers in yard by.
        /// </summary>
        internal static string AgentContainersinyardby {
            get {
                return ResourceManager.GetString("AgentContainersinyardby", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agent Discharged Containers.
        /// </summary>
        internal static string AgentDischargedContainers {
            get {
                return ResourceManager.GetString("AgentDischargedContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agents Vessels Visits Operations.
        /// </summary>
        internal static string AgentsVesselsVisitsOperations {
            get {
                return ResourceManager.GetString("AgentsVesselsVisitsOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agent Terminal TEUs.
        /// </summary>
        internal static string AgentTerminalTEUs {
            get {
                return ResourceManager.GetString("AgentTerminalTEUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agent Yard Inventory.
        /// </summary>
        internal static string AgentYardInventory {
            get {
                return ResourceManager.GetString("AgentYardInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to انواع الاتفاقيات.
        /// </summary>
        internal static string AgreementsTypes {
            get {
                return ResourceManager.GetString("AgreementsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to BackLoad.
        /// </summary>
        internal static string BackLoad {
            get {
                return ResourceManager.GetString("BackLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to backloaded Containers.
        /// </summary>
        internal static string backloadedContainers {
            get {
                return ResourceManager.GetString("backloadedContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to by agents/Container status.
        /// </summary>
        internal static string byagents_Containerstatus {
            get {
                return ResourceManager.GetString("byagents_Containerstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to لوحة مؤشرات القضايا.
        /// </summary>
        internal static string CasesDashbord {
            get {
                return ResourceManager.GetString("CasesDashbord", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Case Type.
        /// </summary>
        internal static string casetype {
            get {
                return ResourceManager.GetString("casetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Container handling operatoins on daily basis.
        /// </summary>
        internal static string Containerhandlingoperatoinsondailybasis {
            get {
                return ResourceManager.GetString("Containerhandlingoperatoinsondailybasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Containers in yard by.
        /// </summary>
        internal static string Containersinyardby {
            get {
                return ResourceManager.GetString("Containersinyardby", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Discharged.
        /// </summary>
        internal static string Discharged {
            get {
                return ResourceManager.GetString("Discharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Discharged Containers.
        /// </summary>
        internal static string DischargedContainers {
            get {
                return ResourceManager.GetString("DischargedContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gate moves.
        /// </summary>
        internal static string Gatemoves {
            get {
                return ResourceManager.GetString("Gatemoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gate Performance.
        /// </summary>
        internal static string GatePerformance {
            get {
                return ResourceManager.GetString("GatePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ignored.
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ignored as not Vaild.
        /// </summary>
        internal static string IgnoredStr {
            get {
                return ResourceManager.GetString("IgnoredStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Information Source.
        /// </summary>
        internal static string InformationSource {
            get {
                return ResourceManager.GetString("InformationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to In Process.
        /// </summary>
        internal static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Judgmentresult.
        /// </summary>
        internal static string Judgmentresult {
            get {
                return ResourceManager.GetString("Judgmentresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Medals Dashboard.
        /// </summary>
        internal static string MedalDashboard {
            get {
                return ResourceManager.GetString("MedalDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إخطار الجهة.
        /// </summary>
        internal static string MedalEkhtar {
            get {
                return ResourceManager.GetString("MedalEkhtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إخطار الجهة بصدور الأمر الأميري.
        /// </summary>
        internal static string MedalEkhtarStr {
            get {
                return ResourceManager.GetString("MedalEkhtarStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Medals Org Types.
        /// </summary>
        internal static string MedalOrgTypes {
            get {
                return ResourceManager.GetString("MedalOrgTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to صدرو الأمر الأميري.
        /// </summary>
        internal static string Medalsader {
            get {
                return ResourceManager.GetString("Medalsader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to الأنواط والأوسمة التي صدر بشأنها أمر أميري.
        /// </summary>
        internal static string MedalsaderStr {
            get {
                return ResourceManager.GetString("MedalsaderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MedalStatus.
        /// </summary>
        internal static string MedalStatus {
            get {
                return ResourceManager.GetString("MedalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to mobile.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Names &amp; Ref.
        /// </summary>
        internal static string NamesRef {
            get {
                return ResourceManager.GetString("NamesRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Received Cases.
        /// </summary>
        internal static string NewStr {
            get {
                return ResourceManager.GetString("NewStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of gate moves.
        /// </summary>
        internal static string Numberofgatemoves {
            get {
                return ResourceManager.GetString("Numberofgatemoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of gate moves by agents.
        /// </summary>
        internal static string Numberofgatemovesbyagents {
            get {
                return ResourceManager.GetString("Numberofgatemovesbyagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of vessels per day.
        /// </summary>
        internal static string Numberofvesselsperday {
            get {
                return ResourceManager.GetString("Numberofvesselsperday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Owner Name.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Part Of Case.
        /// </summary>
        internal static string PartOfCase {
            get {
                return ResourceManager.GetString("PartOfCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to post Date.
        /// </summary>
        internal static string postDate {
            get {
                return ResourceManager.GetString("postDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Proceeded.
        /// </summary>
        internal static string Proceeded {
            get {
                return ResourceManager.GetString("Proceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cases Proceeded.
        /// </summary>
        internal static string ProceededStr {
            get {
                return ResourceManager.GetString("ProceededStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Questions Dashboard.
        /// </summary>
        internal static string QuestionsDashborad {
            get {
                return ResourceManager.GetString("QuestionsDashborad", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Questions Dashboard.
        /// </summary>
        internal static string QuestionsDashborad2 {
            get {
                return ResourceManager.GetString("QuestionsDashborad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to QuestionStstusCOunt.
        /// </summary>
        internal static string QuestionStstusCOunt {
            get {
                return ResourceManager.GetString("QuestionStstusCOunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إحصائية الاسئلة الموجة إلى.
        /// </summary>
        internal static string QuestionTargetCOunt {
            get {
                return ResourceManager.GetString("QuestionTargetCOunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quick.
        /// </summary>
        internal static string Quick {
            get {
                return ResourceManager.GetString("Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Recived.
        /// </summary>
        internal static string Recived {
            get {
                return ResourceManager.GetString("Recived", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ref#.
        /// </summary>
        internal static string Ref {
            get {
                return ResourceManager.GetString("Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ship Side Performance.
        /// </summary>
        internal static string ShipSidePerformance {
            get {
                return ResourceManager.GetString("ShipSidePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistics of agent Backload Container by.
        /// </summary>
        internal static string StatisticsofagentBackloadContainerby {
            get {
                return ResourceManager.GetString("StatisticsofagentBackloadContainerby", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistics of agent discharged Container by.
        /// </summary>
        internal static string StatisticsofagentdischargedContainerby {
            get {
                return ResourceManager.GetString("StatisticsofagentdischargedContainerby", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistics of Agents Vessels Visits.
        /// </summary>
        internal static string StatisticsofAgentsVesselsVisits {
            get {
                return ResourceManager.GetString("StatisticsofAgentsVesselsVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistics of Delivered/Received  Container per.
        /// </summary>
        internal static string StatisticsofDeliveredandReceivedContainerper {
            get {
                return ResourceManager.GetString("StatisticsofDeliveredandReceivedContainerper", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Case Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request more information.
        /// </summary>
        internal static string StrInProcess {
            get {
                return ResourceManager.GetString("StrInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Terminal Daily TEUs.
        /// </summary>
        internal static string TerminalDailyTEUs {
            get {
                return ResourceManager.GetString("TerminalDailyTEUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Masder Dashboard.
        /// </summary>
        internal static string TerminalPerformanceDashboard {
            get {
                return ResourceManager.GetString("TerminalPerformanceDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Terminal TEUs Difference.
        /// </summary>
        internal static string TerminalTEUsDifference {
            get {
                return ResourceManager.GetString("TerminalTEUsDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Terminal Yard Utilization.
        /// </summary>
        internal static string TerminalYardUtilization {
            get {
                return ResourceManager.GetString("TerminalYardUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to TEUs.
        /// </summary>
        internal static string TEUs {
            get {
                return ResourceManager.GetString("TEUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ticket List Manager.
        /// </summary>
        internal static string TicketListManager {
            get {
                return ResourceManager.GetString("TicketListManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tickets Status Rates.
        /// </summary>
        internal static string ticketRate {
            get {
                return ResourceManager.GetString("ticketRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tickets List.
        /// </summary>
        internal static string TicketsList {
            get {
                return ResourceManager.GetString("TicketsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tickets Trend.
        /// </summary>
        internal static string TicketsTrend {
            get {
                return ResourceManager.GetString("TicketsTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total of Delivered Containers.
        /// </summary>
        internal static string TotalofDeliveredContainers {
            get {
                return ResourceManager.GetString("TotalofDeliveredContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total of Recived Containers.
        /// </summary>
        internal static string TotalofRecivedContainers {
            get {
                return ResourceManager.GetString("TotalofRecivedContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total of served vessels.
        /// </summary>
        internal static string Totalofservedvessels {
            get {
                return ResourceManager.GetString("Totalofservedvessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total of Received Cases.
        /// </summary>
        internal static string TotalStr {
            get {
                return ResourceManager.GetString("TotalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total Terminal TEUs.
        /// </summary>
        internal static string TotalTerminalTEUs {
            get {
                return ResourceManager.GetString("TotalTerminalTEUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total Volume Discharge-Loading /Box.
        /// </summary>
        internal static string TotalVolumeDischarge_LoadingBox {
            get {
                return ResourceManager.GetString("TotalVolumeDischarge_LoadingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Transaction Date To.
        /// </summary>
        internal static string TransactionDateTo {
            get {
                return ResourceManager.GetString("TransactionDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Transfer and check.
        /// </summary>
        internal static string TransferStr {
            get {
                return ResourceManager.GetString("TransferStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vessels.
        /// </summary>
        internal static string Vessels {
            get {
                return ResourceManager.GetString("Vessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to View Files.
        /// </summary>
        internal static string ViewFiles {
            get {
                return ResourceManager.GetString("ViewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yard Blocks Reserved / Available space.
        /// </summary>
        internal static string YardBlocksReservedAvailablespace {
            get {
                return ResourceManager.GetString("YardBlocksReservedAvailablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yard Trade Capacity utilization.
        /// </summary>
        internal static string YardTradeCapacityutilization {
            get {
                return ResourceManager.GetString("YardTradeCapacityutilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yard Trade Capaticy TEUs.
        /// </summary>
        internal static string YardTradeCapaticyTEUs {
            get {
                return ResourceManager.GetString("YardTradeCapaticyTEUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yard Utilization.
        /// </summary>
        internal static string YardUtilization {
            get {
                return ResourceManager.GetString("YardUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yearly Boxes Comparison.
        /// </summary>
        internal static string YearlyBoxesComparison {
            get {
                return ResourceManager.GetString("YearlyBoxesComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yearly TEUs Comparison.
        /// </summary>
        internal static string YearlyTEUsComparison {
            get {
                return ResourceManager.GetString("YearlyTEUsComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yearly Vessels Comparison.
        /// </summary>
        internal static string YearlyVesselsComparison {
            get {
                return ResourceManager.GetString("YearlyVesselsComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to اول درجه.
        /// </summary>
        internal static string _TotalCasesDegree1 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to اول درجه مستعجل.
        /// </summary>
        internal static string _TotalCasesDegree2 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to استئناف (ثاني درجة).
        /// </summary>
        internal static string _TotalCasesDegree3 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to استئناف مستعجل.
        /// </summary>
        internal static string _TotalCasesDegree4 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to تمييز.
        /// </summary>
        internal static string _TotalCasesDegree5 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to تمييز مستعجل.
        /// </summary>
        internal static string _TotalCasesDegree6 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إستشكال.
        /// </summary>
        internal static string _TotalCasesDegree7 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to استئناف.
        /// </summary>
        internal static string _TotalCasesDegree8 {
            get {
                return ResourceManager.GetString("_TotalCasesDegree8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalCMGS.
        /// </summary>
        internal static string _TotalCMGS {
            get {
                return ResourceManager.GetString("_TotalCMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalCMGSDESC.
        /// </summary>
        internal static string _TotalCMGSDESC {
            get {
                return ResourceManager.GetString("_TotalCMGSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _Totalmarsoom.
        /// </summary>
        internal static string _Totalmarsoom {
            get {
                return ResourceManager.GetString("_Totalmarsoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalmarsoomSre.
        /// </summary>
        internal static string _TotalmarsoomSre {
            get {
                return ResourceManager.GetString("_TotalmarsoomSre", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to استكمال البيانات.
        /// </summary>
        internal static string _TotalMedalCompleteData {
            get {
                return ResourceManager.GetString("_TotalMedalCompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إعادة للجهة لاستكمال البيانات.
        /// </summary>
        internal static string _TotalMedalCompleteDataStr {
            get {
                return ResourceManager.GetString("_TotalMedalCompleteDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to وزير الديوان.
        /// </summary>
        internal static string _TotalMedalToDewan {
            get {
                return ResourceManager.GetString("_TotalMedalToDewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to التحويل إلى وزير الديوان.
        /// </summary>
        internal static string _TotalMedalToDewanStr {
            get {
                return ResourceManager.GetString("_TotalMedalToDewanStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  وزير الدوله.
        /// </summary>
        internal static string _TotalMedalToMinister {
            get {
                return ResourceManager.GetString("_TotalMedalToMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to التحويل إلى وزير الدوله.
        /// </summary>
        internal static string _TotalMedalToMinisterStr {
            get {
                return ResourceManager.GetString("_TotalMedalToMinisterStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to إجراءات اخرى.
        /// </summary>
        internal static string _TotalOther {
            get {
                return ResourceManager.GetString("_TotalOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to الاتفاقيات  المسجلة بإجراءات اخرى.
        /// </summary>
        internal static string _TotalOtherStr {
            get {
                return ResourceManager.GetString("_TotalOtherStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalPublished.
        /// </summary>
        internal static string _TotalPublished {
            get {
                return ResourceManager.GetString("_TotalPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalPublishedSfd.
        /// </summary>
        internal static string _TotalPublishedSfd {
            get {
                return ResourceManager.GetString("_TotalPublishedSfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_AllDesc.
        /// </summary>
        internal static string _TotalQuestion_AllDesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_AllDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_AllStr.
        /// </summary>
        internal static string _TotalQuestion_AllStr {
            get {
                return ResourceManager.GetString("_TotalQuestion_AllStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_DelaiedDesc.
        /// </summary>
        internal static string _TotalQuestion_DelaiedDesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_DelaiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_DelaiedStr.
        /// </summary>
        internal static string _TotalQuestion_DelaiedStr {
            get {
                return ResourceManager.GetString("_TotalQuestion_DelaiedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to استيفاء.
        /// </summary>
        internal static string _TotalQuestion_Estifaa {
            get {
                return ResourceManager.GetString("_TotalQuestion_Estifaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to عدد الاسئلة البرلمانية التي تحتاج استيفاء بيانات.
        /// </summary>
        internal static string _TotalQuestion_Estifaadesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_Estifaadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_NoAnswerDesc.
        /// </summary>
        internal static string _TotalQuestion_NoAnswerDesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_NoAnswerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_NoAnswerStr.
        /// </summary>
        internal static string _TotalQuestion_NoAnswerStr {
            get {
                return ResourceManager.GetString("_TotalQuestion_NoAnswerStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to تمت الإجابة ( رد جزئي ).
        /// </summary>
        internal static string _TotalQuestion_partial {
            get {
                return ResourceManager.GetString("_TotalQuestion_partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to عدد الاسئلة البرلمانية التي تمت الاجابة عليها بشكل جزئي.
        /// </summary>
        internal static string _TotalQuestion_partialdesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_partialdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_ReliedDesc.
        /// </summary>
        internal static string _TotalQuestion_ReliedDesc {
            get {
                return ResourceManager.GetString("_TotalQuestion_ReliedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalQuestion_Reliedstr.
        /// </summary>
        internal static string _TotalQuestion_Reliedstr {
            get {
                return ResourceManager.GetString("_TotalQuestion_Reliedstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToLaw.
        /// </summary>
        internal static string _TotalToLaw {
            get {
                return ResourceManager.GetString("_TotalToLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToLawStr.
        /// </summary>
        internal static string _TotalToLawStr {
            get {
                return ResourceManager.GetString("_TotalToLawStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToMinistery.
        /// </summary>
        internal static string _TotalToMinistery {
            get {
                return ResourceManager.GetString("_TotalToMinistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToMinisterystr.
        /// </summary>
        internal static string _TotalToMinisterystr {
            get {
                return ResourceManager.GetString("_TotalToMinisterystr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToOmma.
        /// </summary>
        internal static string _TotalToOmma {
            get {
                return ResourceManager.GetString("_TotalToOmma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalToOmmaStr.
        /// </summary>
        internal static string _TotalToOmmaStr {
            get {
                return ResourceManager.GetString("_TotalToOmmaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalUnderStudy.
        /// </summary>
        internal static string _TotalUnderStudy {
            get {
                return ResourceManager.GetString("_TotalUnderStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to _TotalUnderStudyStr.
        /// </summary>
        internal static string _TotalUnderStudyStr {
            get {
                return ResourceManager.GetString("_TotalUnderStudyStr", resourceCulture);
            }
        }
    }
}
