//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GDB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GDB", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Receivable Meter.
        /// </summary>
        internal static string AccountsReceivableMeter {
            get {
                return ResourceManager.GetString("AccountsReceivableMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom 5 Services Segment.
        /// </summary>
        internal static string Bottom5ServicesSegment {
            get {
                return ResourceManager.GetString("Bottom5ServicesSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP / Total Of Declaration.
        /// </summary>
        internal static string CCPTotalOfDeclaration {
            get {
                return ResourceManager.GetString("CCPTotalOfDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP / Total Weight.
        /// </summary>
        internal static string CCPTotalWeight {
            get {
                return ResourceManager.GetString("CCPTotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Forecast View.
        /// </summary>
        internal static string DailyForecastView {
            get {
                return ResourceManager.GetString("DailyForecastView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Revenue Meter.
        /// </summary>
        internal static string DailyRevenueMeter {
            get {
                return ResourceManager.GetString("DailyRevenueMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Volume.
        /// </summary>
        internal static string DailyVolume {
            get {
                return ResourceManager.GetString("DailyVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demmurage Services Revenue.
        /// </summary>
        internal static string DemmurageServicesRevenue {
            get {
                return ResourceManager.GetString("DemmurageServicesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Cargo Revenue.
        /// </summary>
        internal static string ExportCargoRevenue {
            get {
                return ResourceManager.GetString("ExportCargoRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Zone.
        /// </summary>
        internal static string FreeZone {
            get {
                return ResourceManager.GetString("FreeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Panel.
        /// </summary>
        internal static string GDB_BudgetPanel {
            get {
                return ResourceManager.GetString("GDB_BudgetPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Revenue Panel.
        /// </summary>
        internal static string GDB_CustomizedRevenuePanel {
            get {
                return ResourceManager.GetString("GDB_CustomizedRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Revenue Panel.
        /// </summary>
        internal static string GDB_DailyRevenuePanel {
            get {
                return ResourceManager.GetString("GDB_DailyRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Revenue Panel.
        /// </summary>
        internal static string GDB_MonthlyRevenuePanel {
            get {
                return ResourceManager.GetString("GDB_MonthlyRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Volume Panel.
        /// </summary>
        internal static string GDB_MonthlyVolumePanel {
            get {
                return ResourceManager.GetString("GDB_MonthlyVolumePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Services Revenue.
        /// </summary>
        internal static string HandlingServicesRevenue {
            get {
                return ResourceManager.GetString("HandlingServicesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Cargo Revenue.
        /// </summary>
        internal static string ImportCargoRevenue {
            get {
                return ResourceManager.GetString("ImportCargoRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Services Revenue.
        /// </summary>
        internal static string ITServicesRevenue {
            get {
                return ResourceManager.GetString("ITServicesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        internal static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Port Forecast View May 2016.
        /// </summary>
        internal static string MonthlyPortForecastViewMay2016 {
            get {
                return ResourceManager.GetString("MonthlyPortForecastViewMay2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Service Type Forecast View.
        /// </summary>
        internal static string MonthlyServiceTypeForecastView {
            get {
                return ResourceManager.GetString("MonthlyServiceTypeForecastView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string moreinfo {
            get {
                return ResourceManager.GetString("moreinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRN Type Compare.
        /// </summary>
        internal static string MRNTypeCompare {
            get {
                return ResourceManager.GetString("MRNTypeCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port / Mean Of Transport.
        /// </summary>
        internal static string PortMeanOfTransport {
            get {
                return ResourceManager.GetString("PortMeanOfTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port / No Of Consignee.
        /// </summary>
        internal static string PortNoOfConsignee {
            get {
                return ResourceManager.GetString("PortNoOfConsignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports Volume.
        /// </summary>
        internal static string PortsVolume {
            get {
                return ResourceManager.GetString("PortsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port / Total Weight.
        /// </summary>
        internal static string PortTotalWeight {
            get {
                return ResourceManager.GetString("PortTotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Type / Total Weight.
        /// </summary>
        internal static string PortTypeTotalWeight {
            get {
                return ResourceManager.GetString("PortTypeTotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue by import/export cargo.
        /// </summary>
        internal static string Revenuebyimportexportcargo {
            get {
                return ResourceManager.GetString("Revenuebyimportexportcargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue By Port.
        /// </summary>
        internal static string RevenueByPort {
            get {
                return ResourceManager.GetString("RevenueByPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue By Port &amp; Service Segment.
        /// </summary>
        internal static string RevenueByPortandServiceSegment {
            get {
                return ResourceManager.GetString("RevenueByPortandServiceSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue By Port &amp; Service Type.
        /// </summary>
        internal static string RevenueByPortServiceType {
            get {
                return ResourceManager.GetString("RevenueByPortServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue by services for import/export.
        /// </summary>
        internal static string Revenuebyservicesforimportexport {
            get {
                return ResourceManager.GetString("Revenuebyservicesforimportexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea.
        /// </summary>
        internal static string Sea {
            get {
                return ResourceManager.GetString("Sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        internal static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Segment - Handling.
        /// </summary>
        internal static string ServiceSegmentHandling {
            get {
                return ResourceManager.GetString("ServiceSegmentHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Segment - IT.
        /// </summary>
        internal static string ServiceSegmentIT {
            get {
                return ResourceManager.GetString("ServiceSegmentIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Display Mode.
        /// </summary>
        internal static string SummaryDisplayMode {
            get {
                return ResourceManager.GetString("SummaryDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Service Segment.
        /// </summary>
        internal static string Top5ServiceSegment {
            get {
                return ResourceManager.GetString("Top5ServiceSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Revenue.
        /// </summary>
        internal static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
    }
}
