//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement_procedureHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreement_procedureHistory()
        {
            this.Agreement_Attachments = new HashSet<Agreement_Attachments>();
        }
    
        public int Code { get; set; }
        public Nullable<int> AgreementCode { get; set; }
        public Nullable<int> ProcedureTypeCode { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<int> Actionby { get; set; }
        public string Remarks { get; set; }
        public string decisionNum { get; set; }
        public Nullable<int> RelatedOrgID { get; set; }
        public string RelatedOrgName { get; set; }
        public Nullable<int> publishType { get; set; }
        public string CMGSDessionNum { get; set; }
        public string CMGSDessionFile { get; set; }
        public string publishDessionFile { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement_Attachments> Agreement_Attachments { get; set; }
        public virtual Agreement_ProcedureTypes Agreement_ProcedureTypes { get; set; }
        public virtual AgreementData AgreementData { get; set; }
    }
}
