//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgreementData()
        {
            this.Agreement_procedureHistory = new HashSet<Agreement_procedureHistory>();
        }
    
        public int Code { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Agr_Serial { get; set; }
        public Nullable<System.DateTime> Agr_ReciveDate { get; set; }
        public Nullable<System.DateTime> Agr_PublishDate { get; set; }
        public Nullable<int> Agr_OrgID { get; set; }
        public Nullable<int> Agr_TypeCode { get; set; }
        public Nullable<int> Agr_CatID { get; set; }
        public string Agr_Subject { get; set; }
        public string Agr_SubjectEn { get; set; }
        public Nullable<System.DateTime> Agr_StartDate { get; set; }
        public Nullable<System.DateTime> Agr_EndDate { get; set; }
        public string SignedBy { get; set; }
        public Nullable<int> LastActionID { get; set; }
        public Nullable<int> StatusCodeID { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<int> Agr_SerialNum { get; set; }
        public Nullable<int> Agr_SerialYear { get; set; }
        public Nullable<bool> isInitial { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Agr_CMGSInitailFile { get; set; }
        public string Agr_CMGSFinalFile { get; set; }
        public Nullable<int> Agr_RelatedOrgId { get; set; }
        public Nullable<int> LastProcedureRefId { get; set; }
        public Nullable<int> Law_DocDataRefId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> assignedPersonID { get; set; }
    
        public virtual Agreement_Category Agreement_Category { get; set; }
        public virtual Agreement_Orgs Agreement_Orgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement_procedureHistory> Agreement_procedureHistory { get; set; }
        public virtual Agreement_TypeCodes Agreement_TypeCodes { get; set; }
    }
}
