//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog_UserOperations
    {
        public long Code { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> moduleCode { get; set; }
        public string userModule { get; set; }
        public string userFunction { get; set; }
        public string url { get; set; }
        public string tages { get; set; }
        public string queryResult { get; set; }
        public Nullable<int> resultCount { get; set; }
        public string RequestDetails { get; set; }
        public string UserHostName { get; set; }
        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }
    }
}
