//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_FileInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case_FileInformation()
        {
            this.Cases_Data = new HashSet<Cases_Data>();
        }
    
        public int Code { get; set; }
        public string file_Serial { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastTransctionDate { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public string FileNote { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> FileInternalSerial { get; set; }
        public Nullable<int> fileSerialyear { get; set; }
        public Nullable<int> assignedPersonID { get; set; }
        public string FileAutoNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Case_AssignedPersons Case_AssignedPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_Data> Cases_Data { get; set; }
    }
}
