//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases_Data()
        {
            this.Case_parties = new HashSet<Case_parties>();
            this.Cases_H_Hearing = new HashSet<Cases_H_Hearing>();
        }
    
        public int Code { get; set; }
        public string CaseSerial { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<int> CaseType { get; set; }
        public string SuitType { get; set; }
        public string SuitNum { get; set; }
        public string SuitYear { get; set; }
        public string CaseSubject { get; set; }
        public string CaseNotes { get; set; }
        public Nullable<int> LastActionID { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<System.DateTime> NexthearingDate { get; set; }
        public Nullable<int> CaseStatus { get; set; }
        public Nullable<int> FileNumID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> CaseDecisionID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> CaseSerialNum { get; set; }
        public Nullable<int> CaseSerialYear { get; set; }
        public string CaseInternalSerial { get; set; }
        public Nullable<int> Judgmentresult { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> CaseMainType { get; set; }
    
        public virtual Case_FileInformation Case_FileInformation { get; set; }
        public virtual Case_LitigationDegree Case_LitigationDegree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case_parties> Case_parties { get; set; }
        public virtual Cases_decision Cases_decision { get; set; }
        public virtual Cases_M_DecisionResut Cases_M_DecisionResut { get; set; }
        public virtual Cases_M_Status Cases_M_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_H_Hearing> Cases_H_Hearing { get; set; }
        public virtual Cases_M_CaseTypes Cases_M_CaseTypes { get; set; }
    }
}
