//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints_Data
    {
        public int Code { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<int> Complaints_Num { get; set; }
        public Nullable<int> Complaints_Year { get; set; }
        public string Complaints_Serial { get; set; }
        public Nullable<System.DateTime> Complaints_Date { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Complaints_OwnerName { get; set; }
        public Nullable<int> RelatedCommitteid { get; set; }
        public Nullable<int> RelatedOrgId { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string Complaints_Subject { get; set; }
        public string Notes { get; set; }
        public string Complaints_File { get; set; }
        public Nullable<bool> NoRelated { get; set; }
        public Nullable<int> Complaints_Type { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
