//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_DocProcedures
    {
        public int Code { get; set; }
        public Nullable<int> ProcedureTypeID { get; set; }
        public Nullable<int> DocRefID { get; set; }
        public string ProcedureletterNum { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string ProcedureSubject { get; set; }
        public string ProcedureNotes { get; set; }
        public Nullable<bool> SendToOma { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string Procedureattachments { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Law_DocData Law_DocData { get; set; }
        public virtual law_DocProceduresTypes law_DocProceduresTypes { get; set; }
    }
}
