//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_DocCategory
    {
        public int Code { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public Nullable<int> TypeID { get; set; }
    }
}
