//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalMemo
    {
        public int Code { get; set; }
        public Nullable<int> DocCategoryId { get; set; }
        public string DocSerial { get; set; }
        public Nullable<int> FileNum { get; set; }
        public Nullable<int> DocYear { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ProcedureId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string DocSubject { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<bool> UnderStudy { get; set; }
        public string DocFilepath { get; set; }
        public string DocDetails { get; set; }
        public string DocNotes { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> assignedEmp { get; set; }
        public Nullable<int> DocStatusId { get; set; }
        public Nullable<int> ConsultantId { get; set; }
    
        public virtual LegalMemo_AssignedPersons LegalMemo_AssignedPersons { get; set; }
        public virtual LegalMemo_Category LegalMemo_Category { get; set; }
        public virtual LegalMemo_Org LegalMemo_Org { get; set; }
        public virtual LegalMemo_Procedure LegalMemo_Procedure { get; set; }
        public virtual LegalMemo_Status LegalMemo_Status { get; set; }
    }
}
