//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal_ProcedureHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medal_ProcedureHistory()
        {
            this.Medal_Attachments = new HashSet<Medal_Attachments>();
        }
    
        public int Code { get; set; }
        public Nullable<int> MedalMasterID { get; set; }
        public Nullable<int> ProcedureTypeCode { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<int> Actionby { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medal_Attachments> Medal_Attachments { get; set; }
        public virtual Medal_Data Medal_Data { get; set; }
        public virtual Medal_M_ProcedureType Medal_M_ProcedureType { get; set; }
    }
}
