//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal_M_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medal_M_Types()
        {
            this.Medal_Persons = new HashSet<Medal_Persons>();
        }
    
        public int Code { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual Medal_M_Category Medal_M_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medal_Persons> Medal_Persons { get; set; }
    }
}
