//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal_Persons
    {
        public int Code { get; set; }
        public Nullable<int> MedalmasterID { get; set; }
        public int MedalType { get; set; }
        public Nullable<int> MedalTypeCatID { get; set; }
        public string Person_NameEn { get; set; }
        public string Person_NameAr { get; set; }
        public string CivilID { get; set; }
        public string MilitaryNum { get; set; }
        public Nullable<int> GrantReason { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string GrantReasonText { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PersonTitle { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual Medal_Data Medal_Data { get; set; }
        public virtual Medal_M_jobGrade Medal_M_jobGrade { get; set; }
        public virtual Medal_M_Types Medal_M_Types { get; set; }
    }
}
