//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parliament_RelatedOrgs
    {
        public int Code { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string OrgName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> aUser { get; set; }
    
        public virtual Parliament_Questions Parliament_Questions { get; set; }
    }
}
