//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pm_Letters
    {
        public int code { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Arc_Num { get; set; }
        public Nullable<int> Arc_Year { get; set; }
        public string Arc_Serial { get; set; }
        public Nullable<System.DateTime> Arc_Date { get; set; }
        public string Arc_Attachment { get; set; }
        public string Arc_Subject { get; set; }
        public string Arc_Notes { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Pm_Letters_Categories Pm_Letters_Categories { get; set; }
    }
}
