//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUser_AuditLog
    {
        public string AuditType { get; set; }
        public string TableName { get; set; }
        public string PK { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string TabaleNameEn { get; set; }
        public string TabaleNameAr { get; set; }
        public string DeptnameEn { get; set; }
        public string DeptNameAr { get; set; }
        public string NO { get; set; }
        public string ModuleName { get; set; }
    }
}
