//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CasesList
    {
        public string GroupName { get; set; }
        public string file_Serial { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastTransctionDate { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> FileNumID { get; set; }
        public int CaseID { get; set; }
        public string CaseSerial { get; set; }
        public Nullable<System.DateTime> CaseCreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public string CasesTypeEn { get; set; }
        public string CasesTypeAr { get; set; }
        public string SuitType { get; set; }
        public string SuitNum { get; set; }
        public string SuitYear { get; set; }
        public string CaseSubject { get; set; }
        public string CaseNotes { get; set; }
        public Nullable<int> LastActionID { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<System.DateTime> NexthearingDate { get; set; }
        public Nullable<int> CaseStatus { get; set; }
        public string CaseStatusEn { get; set; }
        public string CaseStatusAr { get; set; }
        public Nullable<int> CaseType { get; set; }
        public Nullable<System.DateTime> CaseTransDate { get; set; }
        public int Code { get; set; }
        public string LitigationDegreeEn { get; set; }
        public string LitigationDegreeAr { get; set; }
        public string DecisionNameEn { get; set; }
        public string DecisionNameAr { get; set; }
        public string FileNote { get; set; }
        public Nullable<int> FileInternalSerial { get; set; }
        public Nullable<int> fileSerialyear { get; set; }
        public Nullable<int> assignedPersonID { get; set; }
        public Nullable<int> CaseDecisionID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> CaseSerialNum { get; set; }
        public Nullable<int> CaseSerialYear { get; set; }
        public string CaseInternalSerial { get; set; }
        public string caseAssignedPersonsNameEn { get; set; }
        public string caseAssignedPersonsNameAr { get; set; }
        public Nullable<int> attachmentCount { get; set; }
        public string Judgmentresult { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> Fileisdeleted { get; set; }
        public Nullable<int> JudgmentresultId { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> CaseMainType { get; set; }
        public string CasesMainTypeEn { get; set; }
        public string CasesMainTypeAr { get; set; }
    }
}
