//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_QuestionsList
    {
        public string GroupName { get; set; }
        public Nullable<int> D_Order { get; set; }
        public Nullable<int> sessionOrder { get; set; }
        public Nullable<int> QType { get; set; }
        public int code { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public int Q_Serial { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> OmaYear { get; set; }
        public Nullable<int> Q_RequestTo { get; set; }
        public string Q_Text { get; set; }
        public string Q_Attachment { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<System.DateTime> Q_Date { get; set; }
        public Nullable<int> AssignedPersonID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Q_Notes { get; set; }
        public string ChapterNameEn { get; set; }
        public string ChapterNameAr { get; set; }
        public string StatusNameEn { get; set; }
        public string StatusNameAr { get; set; }
        public string SessionNameEn { get; set; }
        public string SessionNameAr { get; set; }
        public string AssignedPersonNameEn { get; set; }
        public string AssignedPersonNameAr { get; set; }
        public string Q_RequestToNameEn { get; set; }
        public string Q_RequestToNameAr { get; set; }
        public Nullable<bool> Is_grouped { get; set; }
        public string Oma_Serial { get; set; }
        public string RequestedFromNameEn { get; set; }
        public string ResultNameEn { get; set; }
        public string ResultNameAr { get; set; }
        public Nullable<int> Q_Result { get; set; }
        public string RequestedFromNameAr { get; set; }
        public Nullable<System.DateTime> Q_DiscussionDate { get; set; }
        public Nullable<int> madbataRefId { get; set; }
        public Nullable<int> Q_RequestFrom { get; set; }
        public string M_Serial { get; set; }
        public Nullable<System.DateTime> M_Date { get; set; }
        public string M_Attachment { get; set; }
        public Nullable<int> Q_Result_VoteWith { get; set; }
        public Nullable<int> Q_Result_VoteAgainst { get; set; }
        public Nullable<int> Q_Result_Void { get; set; }
        public Nullable<int> Q_Result_absent { get; set; }
        public string RelatedOrgs { get; set; }
        public string RequestedFrompersons { get; set; }
    }
}
