//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MadbataList
    {
        public string GroupName { get; set; }
        public int code { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string M_Serial { get; set; }
        public Nullable<System.DateTime> M_Date { get; set; }
        public string M_Attachment { get; set; }
        public string M_Notes { get; set; }
        public Nullable<int> aUser { get; set; }
        public string ChapterNameEn { get; set; }
        public string ChapterNameAr { get; set; }
        public string SessionNameEn { get; set; }
        public string SessionNameAr { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> D_Order { get; set; }
    }
}
