//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AgreeementsList
    {
        public string GroupName { get; set; }
        public int Code { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Agr_Serial { get; set; }
        public Nullable<System.DateTime> Agr_ReciveDate { get; set; }
        public Nullable<System.DateTime> Agr_PublishDate { get; set; }
        public string AgreementOrgNameEn { get; set; }
        public string AgreementOrgNameAr { get; set; }
        public Nullable<int> OrgType { get; set; }
        public Nullable<int> Agr_OrgID { get; set; }
        public Nullable<int> Agr_TypeCode { get; set; }
        public string AgreementTypeNameEn { get; set; }
        public string AgreementTypeNameAr { get; set; }
        public string AgreementCatNameEn { get; set; }
        public string AgreementCatNameAr { get; set; }
        public Nullable<int> Agr_CatID { get; set; }
        public string Agr_Subject { get; set; }
        public string Agr_SubjectEn { get; set; }
        public Nullable<System.DateTime> Agr_StartDate { get; set; }
        public Nullable<System.DateTime> Agr_EndDate { get; set; }
        public string SignedBy { get; set; }
        public Nullable<int> LastActionID { get; set; }
        public Nullable<int> StatusCodeID { get; set; }
        public string StatusNameEn { get; set; }
        public string StatusNameAr { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<int> Agr_SerialNum { get; set; }
        public Nullable<int> Agr_SerialYear { get; set; }
        public Nullable<bool> isInitial { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string LastProcedureNameEn { get; set; }
        public string LastProcedureNameAr { get; set; }
        public string Agr_CMGSInitailFile { get; set; }
        public string Agr_CMGSFinalFile { get; set; }
        public Nullable<int> Agr_RelatedOrgId { get; set; }
        public string RelatedOrgNameEn { get; set; }
        public string RelatedOrgNameAr { get; set; }
        public Nullable<int> LastProcedureRefId { get; set; }
        public Nullable<int> Law_DocDataRefId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string lawfile { get; set; }
        public Nullable<int> assignedPersonID { get; set; }
    }
}
