//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LawsLinkedDocs
    {
        public string GroupName { get; set; }
        public int linkedID { get; set; }
        public Nullable<int> SouceDocID { get; set; }
        public Nullable<int> DestDocId { get; set; }
        public int Code { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string DocSerial { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> DocYear { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string DocSubject { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<bool> UnderStudy { get; set; }
        public Nullable<int> DocCategoryID { get; set; }
        public Nullable<bool> isPublished { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string PublishVersion { get; set; }
        public string DocFilepath { get; set; }
        public string DocNotes { get; set; }
        public Nullable<int> LastProcedureID { get; set; }
        public Nullable<int> aUser { get; set; }
        public string Law_DocTypeNameEn { get; set; }
        public string Law_DocTypeNameAr { get; set; }
        public string Law_DocCategoryNameEn { get; set; }
        public string Law_DocCategoryNameAr { get; set; }
        public Nullable<int> ProcedureTypeID { get; set; }
        public Nullable<int> DocRefID { get; set; }
        public string ProcedureletterNum { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string ProcedureSubject { get; set; }
        public string ProcedureNotes { get; set; }
        public Nullable<bool> SendToOma { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string law_DocProceduresTypesNameEn { get; set; }
        public string law_DocProceduresTypesNameAr { get; set; }
        public string kng_Dession { get; set; }
        public string DocFilepath_published { get; set; }
        public string DocDetails { get; set; }
        public Nullable<int> relatedAgreement { get; set; }
        public Nullable<int> ProcedureTypeCode { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
