//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MedalData
    {
        public int Code { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string FileNum { get; set; }
        public Nullable<System.DateTime> Medal_receivedDate { get; set; }
        public Nullable<int> Medal_OrgID { get; set; }
        public string OrgNameEn { get; set; }
        public string OrgNameAr { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> aUser { get; set; }
        public Nullable<int> LastActionID { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<int> OrgType { get; set; }
        public Nullable<int> FileSerial { get; set; }
        public Nullable<int> FileYear { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public Nullable<int> RelatedLawDocRefId { get; set; }
        public Nullable<int> MedalCatId { get; set; }
    }
}
