//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permission.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggerMatrix
    {
        public int Code { get; set; }
        public string LogMessage { get; set; }
        public string Type { get; set; }
        public string ExchangeID { get; set; }
    }
}
