//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permission.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_pr_Permission
    {
        public int code { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> sysid { get; set; }
        public Nullable<int> pageid { get; set; }
        public Nullable<int> jobid { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<bool> modify { get; set; }
        public Nullable<bool> AddRecord { get; set; }
        public Nullable<bool> DeleteRecord { get; set; }
        public Nullable<bool> DateControl { get; set; }
    }
}
