//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permission.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserSystems
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string SystemNameAr { get; set; }
        public int code { get; set; }
        public string SystemNameEn { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isOperation { get; set; }
        public string deptName { get; set; }
    }
}
